/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import BLL.ImportBLL;
import DAL.StatisticsDAL;
import POJO.category;
import POJO.orderdetail;
import POJO.vegetable;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author tantaiAdmin
 */
public class ImportDetail extends javax.swing.JFrame {
    ImportBLL bLL;
    /**
     * Creates new form NhaphangEdit
     */
    //
    public ImportDetail(String ID, String Name, String Unit, String Amount, String Image, String Price) {
        initComponents();
        bLL = new ImportBLL();
        txt_vegetableIDEdit.setText(ID);
        txt_VegetableNameEdit.setText(Name);
        txt_UnitEdit.setText(Unit);
        txt_AmountEdit.setText(Amount);
        txt_ImageEdit.setText(Image);
        txt_PriceEdit.setText(Price);
        showcombobox();
        getCategoryName(ID);
    }
    private void showcombobox(){
        Box_categoryNameEdit.removeAllItems();
        List<category> list = bLL.loadCategory();
        for (int i = 0; i < list.size(); i++) {
            Box_categoryNameEdit.addItem(list.get(i).getName());
        }
    }
    private void getCategoryName(String ID){
        String name;
        int Ids= Integer.valueOf(ID);
        vegetable idvg = bLL.getProductByID(Ids);
        category cate= bLL.getDanhMuc(idvg.getCatagoryID().getCatagoryID());
        name=cate.getName();
        Box_categoryNameEdit.setSelectedItem(name);
    }
    private ImportDetail() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_vegetableIDEdit = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_VegetableNameEdit = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_UnitEdit = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_AmountEdit = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_ImageEdit = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_PriceEdit = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Box_categoryNameEdit = new javax.swing.JComboBox<>();
        Edit_NHEdit = new javax.swing.JButton();
        Delete_NHEdit = new javax.swing.JButton();
        Back_NHEdit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Product Detail");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("VegetableID");

        txt_vegetableIDEdit.setEditable(false);
        txt_vegetableIDEdit.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setText("VegetableName");

        txt_VegetableNameEdit.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("Unit");

        txt_UnitEdit.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("Amount");

        txt_AmountEdit.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel7.setText("Image");

        txt_ImageEdit.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel8.setText("Price");

        txt_PriceEdit.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel6.setText("CatagoryName");

        Edit_NHEdit.setBackground(new java.awt.Color(204, 204, 255));
        Edit_NHEdit.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Edit_NHEdit.setText("Save");
        Edit_NHEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Edit_NHEditActionPerformed(evt);
            }
        });

        Delete_NHEdit.setBackground(new java.awt.Color(255, 153, 153));
        Delete_NHEdit.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Delete_NHEdit.setText("Detele");
        Delete_NHEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Delete_NHEditActionPerformed(evt);
            }
        });

        Back_NHEdit.setBackground(new java.awt.Color(255, 255, 204));
        Back_NHEdit.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Back_NHEdit.setText("Back");
        Back_NHEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back_NHEditActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Back_NHEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Edit_NHEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(Delete_NHEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Box_categoryNameEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(txt_VegetableNameEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txt_vegetableIDEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txt_UnitEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txt_AmountEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txt_ImageEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txt_PriceEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(96, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_vegetableIDEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_VegetableNameEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_UnitEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_AmountEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_ImageEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_PriceEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Box_categoryNameEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Delete_NHEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Back_NHEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Edit_NHEdit))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Back_NHEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back_NHEditActionPerformed
        // TODO add your handling code here:
        ImportReport nh= new ImportReport();
        nh.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Back_NHEditActionPerformed

    private void Edit_NHEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Edit_NHEditActionPerformed
        // TODO add your handling code here:
        if(txt_vegetableIDEdit.getText().equals("")||txt_VegetableNameEdit.getText().equals("")||
                txt_UnitEdit.getText().equals("")||txt_AmountEdit.getText().equals("")||
                txt_ImageEdit.getText().equals("")||txt_PriceEdit.getText().equals("") ){
            JOptionPane.showMessageDialog(rootPane, "Vui lòng không để trống");
        }
        else{
            int repose=JOptionPane.showConfirmDialog(rootPane, "Đồng ý sửa ?","Confirm", JOptionPane.YES_NO_OPTION);
            if(repose==JOptionPane.YES_OPTION){
            vegetable vg = bLL.getProductByID(Integer.valueOf(txt_vegetableIDEdit.getText()));
            vg.setCatagoryID(traveidsanpham(Box_categoryNameEdit.getSelectedItem().toString()));
           vg.setVegetableName(txt_VegetableNameEdit.getText());
           vg.setUnit(txt_UnitEdit.getText());
           vg.setAmount(Integer.valueOf(txt_AmountEdit.getText()));
           vg.setImage(txt_ImageEdit.getText());
           vg.setPrice(Float.valueOf(txt_PriceEdit.getText()));
           JOptionPane.showMessageDialog(rootPane, "Sửa thành công!");
           bLL.updateProduct(vg);
           Quaylai();
        }
        }
    }//GEN-LAST:event_Edit_NHEditActionPerformed

    private void Delete_NHEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Delete_NHEditActionPerformed
        // TODO add your handling code here:
       int repose=JOptionPane.showConfirmDialog(rootPane, "Đồng ý xóa ?","Confirm", JOptionPane.YES_NO_OPTION);
       if(repose==JOptionPane.YES_OPTION){
           vegetable vg = bLL.getProductByID(Integer.valueOf(txt_vegetableIDEdit.getText()));
            bLL.deleteProduct(vg);
            JOptionPane.showMessageDialog(rootPane, "Đã xóa");
            Quaylai();
        }
    }//GEN-LAST:event_Delete_NHEditActionPerformed
  public category traveidsanpham(String name){
        List<category> catelist= bLL.loadCategory();
        for (int i = 0; i < catelist.size(); i++) {
            if(catelist.get(i).getName().equals(name)){
                return catelist.get(i);
            }
        }
        return null;
    }
    public void Quaylai(){
        ImportReport jf= new ImportReport();
        jf.setVisible(true);
        jf.setLocationRelativeTo(null);
        this.dispose();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ImportDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ImportDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ImportDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ImportDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ImportDetail().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back_NHEdit;
    private javax.swing.JComboBox<String> Box_categoryNameEdit;
    private javax.swing.JButton Delete_NHEdit;
    private javax.swing.JButton Edit_NHEdit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txt_AmountEdit;
    private javax.swing.JTextField txt_ImageEdit;
    private javax.swing.JTextField txt_PriceEdit;
    private javax.swing.JTextField txt_UnitEdit;
    private javax.swing.JTextField txt_VegetableNameEdit;
    private javax.swing.JTextField txt_vegetableIDEdit;
    // End of variables declaration//GEN-END:variables
}
