/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import POJO.*;
import BLL.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author tantaiAdmin
 */
public class ImportReport extends javax.swing.JFrame implements ActionListener{
    ImportBLL nhaphangBLL;
    /**
     * Creates new form NhapHangJFrame
     */
    public ImportReport() {
        initComponents();
        nhaphangBLL = new ImportBLL();
        this.setLocationRelativeTo(null);
        loadTableNhaphang();
    }
    private void loadTableNhaphang(){
        List ls = nhaphangBLL.loadVegetable();
        Object[][] modelOBJ;
        modelOBJ = nhaphangBLL.convertList(ls);
        String[] title = {"VegetableID ","VegetableName","Unit","Amount","Image","Price"};
        DefaultTableModel model = new DefaultTableModel(modelOBJ,title);
        Table_nhaphang.setModel(model);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table_nhaphang = new javax.swing.JTable();
        txt_TimKiemNH = new javax.swing.JTextField();
        Btn_refeshNH = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        Btn_TimKiemNH = new javax.swing.JButton();
        Btn_EditNH = new javax.swing.JButton();
        Btn_addnewNH = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        jLabel1.setBackground(new java.awt.Color(51, 51, 255));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Search");

        Table_nhaphang.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Table_nhaphang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
            }
        ));
        jScrollPane1.setViewportView(Table_nhaphang);

        Btn_refeshNH.setBackground(new java.awt.Color(204, 204, 255));
        Btn_refeshNH.setText("Refresh");
        Btn_refeshNH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_refeshNHActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(51, 51, 255));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Import");

        Btn_TimKiemNH.setBackground(new java.awt.Color(255, 255, 204));
        Btn_TimKiemNH.setText("Find");
        Btn_TimKiemNH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_TimKiemNHActionPerformed(evt);
            }
        });

        Btn_EditNH.setBackground(new java.awt.Color(255, 204, 255));
        Btn_EditNH.setText("Edit");
        Btn_EditNH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_EditNHActionPerformed(evt);
            }
        });

        Btn_addnewNH.setBackground(new java.awt.Color(255, 153, 204));
        Btn_addnewNH.setText("Import");
        Btn_addnewNH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_addnewNHActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Btn_addnewNH, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 597, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txt_TimKiemNH, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(Btn_TimKiemNH)
                            .addGap(50, 50, 50)
                            .addComponent(Btn_refeshNH, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Btn_EditNH, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 14, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_TimKiemNH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(Btn_TimKiemNH)
                    .addComponent(Btn_refeshNH)
                    .addComponent(Btn_EditNH))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Btn_addnewNH)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_TimKiemNHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_TimKiemNHActionPerformed
        // TODO add your handling code here:
        if(txt_TimKiemNH.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Input text for searching!");
        }
        else{
        String nhap = txt_TimKiemNH.getText();
        List ls = nhaphangBLL.findProduct(nhap);
        Object[][] modelOBJ;
        modelOBJ = nhaphangBLL.convertList(ls);
        String[] title = {"VegetableID ","VegetableName","Unit","Amount","Image","Price"};
        DefaultTableModel model = new DefaultTableModel(modelOBJ,title);
        Table_nhaphang.setModel(model);
        }
    }//GEN-LAST:event_Btn_TimKiemNHActionPerformed

    private void Btn_refeshNHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_refeshNHActionPerformed
        // TODO add your handling code here:
        
        loadTableNhaphang();
    }//GEN-LAST:event_Btn_refeshNHActionPerformed

    private void Btn_addnewNHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_addnewNHActionPerformed
        // TODO add your handling code here:
        NewImport new2 = new NewImport();
        new2.setVisible(true);
        new2.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_Btn_addnewNHActionPerformed

    private void Btn_EditNHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_EditNHActionPerformed
        // TODO add your handling code here:
        int row=Table_nhaphang.getSelectedRow();
        if(row<0){
        JOptionPane.showMessageDialog(rootPane, "Select the line to see detail!");}
        else{
        String ID = Table_nhaphang.getValueAt(row, 0).toString();
        String Name =Table_nhaphang.getValueAt(row, 1).toString();
        String Unit =Table_nhaphang.getValueAt(row, 2).toString();
        String Amount =Table_nhaphang.getValueAt(row, 3).toString();
        String Image =Table_nhaphang.getValueAt(row, 4).toString();
        String Price =Table_nhaphang.getValueAt(row, 5).toString();
        
        ImportDetail New1= new ImportDetail(ID , Name, Unit, Amount, Image, Price);
        New1.setVisible(true);
        New1.setLocationRelativeTo(null);
        this.dispose();
        }
    }//GEN-LAST:event_Btn_EditNHActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ImportReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ImportReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ImportReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ImportReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ImportReport().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_EditNH;
    private javax.swing.JButton Btn_TimKiemNH;
    private javax.swing.JButton Btn_addnewNH;
    private javax.swing.JButton Btn_refeshNH;
    private javax.swing.JTable Table_nhaphang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txt_TimKiemNH;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
