/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import BLL.ReceiptBLL;
import BLL.ImportBLL;
import BLL.StatisticsBLL;
import BLL.CustomersBLL;
import POJO.customers;
import POJO.orderdetail;
import POJO.orderproduct;
import POJO.vegetable;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author tantaiAdmin
 */
public class NewReceipt extends javax.swing.JFrame {
    ReceiptBLL hdBLL;
    ImportBLL nhaphangBLL;
    ArrayList<vegetable>vglis;
    public float tongcong=0;
    /**
     * Creates new form HoaDonBanHangNew
     */
    public NewReceipt() {
        initComponents();
        hdBLL = new ReceiptBLL();
        nhaphangBLL = new ImportBLL();
        vglis = new ArrayList<>();
        showcombobox();
        loadTableNhaphang();
    }
    
    private void showcombobox(){
        CustomersBLL cusBLL= new CustomersBLL();
        cb_cus.removeAllItems();
        List<customers> list = cusBLL.loadCustomers();
        for (int i = 0; i < list.size(); i++) {
            cb_cus.addItem(list.get(i).getFullname());
        }
        txt_date.setText(String.valueOf(java.time.LocalDate.now()));
    }
     private void loadTableNhaphang(){
        List ls = nhaphangBLL.loadVegetable();
        Object[][] modelOBJ;
        modelOBJ = nhaphangBLL.convertList(ls);
        String[] title = {"VegetableID ","VegetableName","Unit","Amount","Image","Price"};
        DefaultTableModel model = new DefaultTableModel(modelOBJ,title);
        tb_sp.setModel(model);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_orid = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_ordr_detail = new javax.swing.JTable();
        cb_cus = new javax.swing.JComboBox<>();
        txt_orderID = new javax.swing.JTextField();
        txt_date = new javax.swing.JTextField();
        txt_total = new javax.swing.JTextField();
        txt_note = new javax.swing.JTextField();
        txt_tk_sp = new javax.swing.JTextField();
        bt_find_sp = new javax.swing.JButton();
        bt_fresh_sp = new javax.swing.JButton();
        btn_new_sp = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tb_sp = new javax.swing.JTable();
        bt_del_detail = new javax.swing.JButton();
        btn_addneworder = new javax.swing.JButton();
        back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txt_orid.setBackground(new java.awt.Color(204, 255, 204));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("New Receipt");

        jLabel2.setText("OrderID");

        jLabel3.setText("Customer");

        jLabel4.setText("Date");

        jLabel5.setText("Total");

        jLabel6.setText("Note");

        tb_ordr_detail.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
            }
        ));
        jScrollPane1.setViewportView(tb_ordr_detail);

        txt_date.setEditable(false);

        txt_total.setEditable(false);

        bt_find_sp.setBackground(new java.awt.Color(255, 204, 255));
        bt_find_sp.setText("Search");
        bt_find_sp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_find_spActionPerformed(evt);
            }
        });

        bt_fresh_sp.setBackground(new java.awt.Color(204, 204, 255));
        bt_fresh_sp.setText("Refesh");
        bt_fresh_sp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_fresh_spActionPerformed(evt);
            }
        });

        btn_new_sp.setBackground(new java.awt.Color(255, 153, 204));
        btn_new_sp.setText("Add");
        btn_new_sp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_new_spActionPerformed(evt);
            }
        });

        tb_sp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
            }
        ));
        jScrollPane2.setViewportView(tb_sp);

        bt_del_detail.setBackground(new java.awt.Color(255, 153, 153));
        bt_del_detail.setText("Delete");
        bt_del_detail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_del_detailActionPerformed(evt);
            }
        });

        btn_addneworder.setBackground(new java.awt.Color(255, 153, 204));
        btn_addneworder.setText("Add receipt");
        btn_addneworder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addneworderActionPerformed(evt);
            }
        });

        back.setBackground(new java.awt.Color(255, 255, 204));
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout txt_oridLayout = new javax.swing.GroupLayout(txt_orid);
        txt_orid.setLayout(txt_oridLayout);
        txt_oridLayout.setHorizontalGroup(
            txt_oridLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(txt_oridLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(txt_oridLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bt_del_detail)
                    .addGroup(txt_oridLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(txt_oridLayout.createSequentialGroup()
                            .addGroup(txt_oridLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(txt_oridLayout.createSequentialGroup()
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txt_orderID))
                                .addGroup(txt_oridLayout.createSequentialGroup()
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cb_cus, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(33, 33, 33)
                            .addGroup(txt_oridLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(txt_oridLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txt_date, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                                .addComponent(txt_total))
                            .addGap(18, 18, 18)
                            .addGroup(txt_oridLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(txt_oridLayout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txt_note))
                                .addGroup(txt_oridLayout.createSequentialGroup()
                                    .addGap(0, 0, Short.MAX_VALUE)
                                    .addComponent(btn_addneworder))))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 546, Short.MAX_VALUE)
                        .addComponent(jScrollPane2)
                        .addGroup(txt_oridLayout.createSequentialGroup()
                            .addComponent(txt_tk_sp, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(bt_find_sp)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(bt_fresh_sp, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, txt_oridLayout.createSequentialGroup()
                            .addComponent(back)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_new_sp))))
                .addContainerGap(25, Short.MAX_VALUE))
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        txt_oridLayout.setVerticalGroup(
            txt_oridLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(txt_oridLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(txt_oridLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_orderID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_note, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(txt_oridLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_cus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_addneworder))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(bt_del_detail)
                .addGap(18, 18, 18)
                .addGroup(txt_oridLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_tk_sp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_find_sp)
                    .addComponent(bt_fresh_sp))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(txt_oridLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_new_sp)
                    .addComponent(back))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(txt_orid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txt_orid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_addneworderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addneworderActionPerformed
        // TODO add your handling code here:
        if(txt_orderID.getText().equals("")||txt_note.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "You must fill the ID, Note!");
            
        }
        else{
          boolean kt=true;
        int so = Integer.parseInt(txt_orderID.getText());
        List<orderproduct> list = hdBLL.loadOrder();
        for (int i = 0; i < list.size(); i++) {
            if(list.get(i).getOrderID()==so){
                JOptionPane.showMessageDialog(rootPane, "The ID has already existed, please select another ID!");
                kt=false;
                }
            }
        if(kt==true ){
            if(tb_ordr_detail.getRowCount()==0){
            saveOrder();
            }
            else{
                saveOrder();
                for(vegetable vg : vglis){
                    orderproduct odp = hdBLL.getOrder(Integer.valueOf(txt_orderID.getText()));
                    orderdetail ord1 = new orderdetail();
                    ord1.setOrderID(odp);
                    ord1.setVegetableID(vg);
                    ord1.setQuantity(vg.getAmount());
                    ord1.setPrice(vg.getPrice());
                    StatisticsBLL tkBLL = new StatisticsBLL();
                    tkBLL.addOrderDetail(ord1);
                }
            }
        }
        }
    }//GEN-LAST:event_btn_addneworderActionPerformed

    private void bt_find_spActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_find_spActionPerformed
        // TODO add your handling code here:
                // TODO add your handling code here:
        if(txt_tk_sp.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "You must input text for searching!");
        }
        else{
        String nhap = txt_tk_sp.getText();
        List ls = nhaphangBLL.findProduct(nhap);
        Object[][] modelOBJ;
        modelOBJ = nhaphangBLL.convertList(ls);
        String[] title = {"VegetableID ","VegetableName","Unit","Amount","Image","Price"};
        DefaultTableModel model = new DefaultTableModel(modelOBJ,title);
        tb_sp.setModel(model);
        }
    }//GEN-LAST:event_bt_find_spActionPerformed

    private void bt_fresh_spActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_fresh_spActionPerformed
        // TODO add your handling code here:
        loadTableNhaphang();
    }//GEN-LAST:event_bt_fresh_spActionPerformed

    private void btn_new_spActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_new_spActionPerformed
        // TODO add your handling code here:
        int rows=tb_sp.getSelectedRow();
        if(rows<0){
            JOptionPane.showMessageDialog(rootPane, "Select the line to add to the receipt!");
        }
        else{
                vegetable vg = new vegetable();
                vg.setVegetableID(Integer.valueOf(tb_sp.getValueAt(rows, 0).toString()));
                vg.setVegetableName(tb_sp.getValueAt(rows, 1).toString());
                vg.setUnit(tb_sp.getValueAt(rows, 2).toString());
                vg.setAmount(1);
                vg.setImage(tb_sp.getValueAt(rows, 4).toString());
                vg.setPrice(Float.valueOf(tb_sp.getValueAt(rows, 5).toString()));
                
                    int test= 0;
                    
                    for(vegetable vtest :vglis){
                        if(vtest.getVegetableID()==vg.getVegetableID()){
                            JOptionPane.showMessageDialog(rootPane, "This product has already been added!");
                            test++;
                            }
                   }
                    if(test==0){
                   vglis.add(vg);
                   Object[][] modelOBJ;
                   modelOBJ = nhaphangBLL.convertList(vglis);
                   String[] title = {"VegetableID ","VegetableName","Unit","Amount","Image","Price"};
                   DefaultTableModel model = new DefaultTableModel(modelOBJ,title);
                   tb_ordr_detail.setModel(model);
                   tongcong+=vg.getPrice();
                   txt_total.setText(String.valueOf(tongcong));
                   }
        }
    }//GEN-LAST:event_btn_new_spActionPerformed

    private void bt_del_detailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_del_detailActionPerformed
        // TODO add your handling code here:
       int rows=tb_ordr_detail.getSelectedRow();
        if(rows<0){
            JOptionPane.showMessageDialog(rootPane, "Select the line to delete!");
        }
        else{
            DefaultTableModel models = (DefaultTableModel)tb_ordr_detail.getModel(); 
            tongcong-=Float.valueOf(tb_ordr_detail.getValueAt(rows, 5).toString());
            txt_total.setText(String.valueOf(tongcong));
            vglis.remove(rows);
            models.removeRow(rows);
            
            
        }
    }//GEN-LAST:event_bt_del_detailActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        Quaylai();
    }//GEN-LAST:event_backActionPerformed
    public void saveOrder(){
        try {
            orderproduct od = new orderproduct();
            od.setOrderID(Integer.valueOf(txt_orderID.getText()));
            od.setCustomerID(traveidkhachhang(cb_cus.getSelectedItem().toString()));
            od.setDate(new SimpleDateFormat("yyyy-MM-dd").parse(txt_date.getText()));
            od.setTotal(Float.valueOf(txt_total.getText()));
            od.setNote(txt_note.getText());
            hdBLL.addOrder(od);
            JOptionPane.showMessageDialog(rootPane, "Đã thêm mới");
             Quaylai();
              } catch (ParseException ex) {
                  Logger.getLogger(NewReceipt.class.getName()).log(Level.SEVERE, null, ex);
              }
    }
    public customers traveidkhachhang(String name){
    CustomersBLL cusBLL = new CustomersBLL();
        List<customers> cslist= cusBLL.loadCustomers();
        for (int i = 0; i < cslist.size(); i++) {
            if(cslist.get(i).getFullname().equals(name)){
                return cslist.get(i);
            }
        }
        return null;
    }
public void Quaylai(){
        ReceiptReport jf= new ReceiptReport();
        jf.setVisible(true);
        jf.setLocationRelativeTo(null);
        this.dispose();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewReceipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewReceipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewReceipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewReceipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewReceipt().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton bt_del_detail;
    private javax.swing.JButton bt_find_sp;
    private javax.swing.JButton bt_fresh_sp;
    private javax.swing.JButton btn_addneworder;
    private javax.swing.JButton btn_new_sp;
    private javax.swing.JComboBox<String> cb_cus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tb_ordr_detail;
    private javax.swing.JTable tb_sp;
    private javax.swing.JTextField txt_date;
    private javax.swing.JTextField txt_note;
    private javax.swing.JTextField txt_orderID;
    private javax.swing.JPanel txt_orid;
    private javax.swing.JTextField txt_tk_sp;
    private javax.swing.JTextField txt_total;
    // End of variables declaration//GEN-END:variables
}
