/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import BLL.ReceiptBLL;
import POJO.orderproduct;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.hibernate.type.YesNoType;

/**
 *
 * @author tantaiAdmin
 */
public class ReceiptReport extends javax.swing.JFrame implements ActionListener{
    ReceiptBLL hdBLL;
    /**
     * Creates new form HoaDonBanHang
     */
    public ReceiptReport() {
        initComponents();
        hdBLL = new ReceiptBLL();
         this.setLocationRelativeTo(null);
        loadReceipt();
        
    }
    public void loadReceipt(){
        List ls = hdBLL.loadOrder();
        Object[][] modelOBJ;
        modelOBJ = hdBLL.convertList(ls);
        String[] title = {"OrderID","FullName","Date","Total","Note"};
        DefaultTableModel model = new DefaultTableModel(modelOBJ,title);
        tb_order.setModel(model);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_order = new javax.swing.JTable();
        btn_deltal_ordr = new javax.swing.JButton();
        btn_del_ordr = new javax.swing.JButton();
        btn_new_ordr = new javax.swing.JButton();
        txt_tk_ordr = new javax.swing.JTextField();
        btn_tk_ordr = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btn_refesh_ordr = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Find by OrderID");

        tb_order.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        jScrollPane1.setViewportView(tb_order);

        btn_deltal_ordr.setBackground(new java.awt.Color(153, 204, 255));
        btn_deltal_ordr.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btn_deltal_ordr.setText("View detail");
        btn_deltal_ordr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deltal_ordrActionPerformed(evt);
            }
        });

        btn_del_ordr.setBackground(new java.awt.Color(255, 153, 153));
        btn_del_ordr.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btn_del_ordr.setText("Delete");
        btn_del_ordr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_del_ordrActionPerformed(evt);
            }
        });

        btn_new_ordr.setBackground(new java.awt.Color(255, 153, 204));
        btn_new_ordr.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btn_new_ordr.setText("Add new receipt");
        btn_new_ordr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_new_ordrActionPerformed(evt);
            }
        });

        btn_tk_ordr.setBackground(new java.awt.Color(255, 204, 255));
        btn_tk_ordr.setText("Search");
        btn_tk_ordr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tk_ordrActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Receipt Report");

        btn_refesh_ordr.setBackground(new java.awt.Color(204, 204, 255));
        btn_refesh_ordr.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btn_refesh_ordr.setText("Refresh");
        btn_refesh_ordr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_refesh_ordrActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 544, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txt_tk_ordr)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE))
                            .addComponent(btn_deltal_ordr, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_del_ordr, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                            .addComponent(btn_tk_ordr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(115, 115, 115)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_new_ordr, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                            .addComponent(btn_refesh_ordr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(31, Short.MAX_VALUE))
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_tk_ordr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_tk_ordr)
                    .addComponent(btn_refesh_ordr))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_new_ordr)
                    .addComponent(btn_del_ordr)
                    .addComponent(btn_deltal_ordr))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_tk_ordrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tk_ordrActionPerformed
        // TODO add your handling code here:
        if(txt_tk_ordr.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "You must input text for searching!");
        }
        else{
       int InputText = Integer.valueOf(txt_tk_ordr.getText());
        List ls = hdBLL.findOrder(InputText);
        Object[][] modelOBJ;
        modelOBJ = hdBLL.convertList(ls);
        String[] title = {"OrderID","FullName","Date","Total","Note"};
        DefaultTableModel model = new DefaultTableModel(modelOBJ, title);
        tb_order.setModel(model);
        }
    }//GEN-LAST:event_btn_tk_ordrActionPerformed

    private void btn_refesh_ordrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_refesh_ordrActionPerformed
        // TODO add your handling code here:
        loadReceipt();
    }//GEN-LAST:event_btn_refesh_ordrActionPerformed

    private void btn_new_ordrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_new_ordrActionPerformed
        // TODO add your handling code here:
        NewReceipt new1= new NewReceipt();
        new1.setVisible(true);
        new1.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btn_new_ordrActionPerformed

    private void btn_del_ordrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_del_ordrActionPerformed
        // TODO add your handling code here:
        int rows = tb_order.getSelectedRow();
        if(rows<0){
            JOptionPane.showMessageDialog(rootPane, "Select the line to delete!");
        }
        else{
            int repose=JOptionPane.showConfirmDialog(rootPane, "Are you sure you want to permanently delete it? ?", "", JOptionPane.YES_OPTION);
            if(repose==JOptionPane.YES_OPTION){
                orderproduct op = hdBLL.getOrder(Integer.valueOf(tb_order.getValueAt(rows, 0).toString()));
                DefaultTableModel model = (DefaultTableModel) tb_order.getModel();
                model.removeRow(rows);
                hdBLL.deleteOrder(op);
            }
        }
    }//GEN-LAST:event_btn_del_ordrActionPerformed

    private void btn_deltal_ordrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deltal_ordrActionPerformed
        // TODO add your handling code here:
         int rows = tb_order.getSelectedRow();
        if(rows<0){
            JOptionPane.showMessageDialog(rootPane, "Select the line to see details!");
        }
        else{
              orderproduct op = hdBLL.getOrder(Integer.valueOf(tb_order.getValueAt(rows, 0).toString()));
              ReceiptDetail edit = new ReceiptDetail(op);
              edit.setVisible(true);
              edit.setLocationRelativeTo(null);
              this.dispose();
        }
    }//GEN-LAST:event_btn_deltal_ordrActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReceiptReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReceiptReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReceiptReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReceiptReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReceiptReport().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_del_ordr;
    private javax.swing.JButton btn_deltal_ordr;
    private javax.swing.JButton btn_new_ordr;
    private javax.swing.JButton btn_refesh_ordr;
    private javax.swing.JButton btn_tk_ordr;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tb_order;
    private javax.swing.JTextField txt_tk_ordr;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
